Repository beyond-sw-camp/be12-fin-HOT6-Petlog-BE, pull requests merged in 2025-04, with the labels that each got.

#66 [Feat] 로그인 체크 구현, 카카오 로그인 구현 중
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/hot6/backend/config/SecurityConfig.java
  backend/src/main/java/com/hot6/backend/config/filter/LoginFilter.java
  backend/src/main/java/com/hot6/backend/user/KakaoOAuth2UserService.java
  backend/src/main/java/com/hot6/backend/user/UserController.java
  backend/src/main/java/com/hot6/backend/user/UserService.java
  backend/src/main/java/com/hot6/backend/user/model/UserDto.java
  backend/src/main/resources/application.yml
Labels: enhancement

#77 [Feat] 카카오 로그인 구현 (#6)
  backend/src/main/java/com/hot6/backend/config/SecurityConfig.java
  backend/src/main/java/com/hot6/backend/user/CustomOAuth2UserService.java
  backend/src/main/java/com/hot6/backend/user/KakaoOAuth2UserService.java
  backend/src/main/java/com/hot6/backend/user/OAuth2SuccessHandler.java
  backend/src/main/java/com/hot6/backend/user/model/CustomOAuth2User.java
  backend/src/main/java/com/hot6/backend/user/model/UserDto.java
  backend/src/main/resources/application.yml
Labels: enhancement

#95 [Feat] 이메일 인증 구현 (#88)
  backend/build.gradle
  backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java
  backend/src/main/java/com/hot6/backend/config/filter/JwtFilter.java
  backend/src/main/java/com/hot6/backend/config/filter/LoginFilter.java
  backend/src/main/java/com/hot6/backend/user/CustomOAuth2UserService.java
  backend/src/main/java/com/hot6/backend/user/EmailVerifyRepository.java
  backend/src/main/java/com/hot6/backend/user/UserController.java
  backend/src/main/java/com/hot6/backend/user/UserService.java
  backend/src/main/java/com/hot6/backend/user/model/EmailVerify.java
  backend/src/main/java/com/hot6/backend/user/model/User.java
  backend/src/main/java/com/hot6/backend/user/model/UserDto.java
  backend/src/main/java/com/hot6/backend/utils/JwtUtil.java
  backend/src/main/resources/application.yml
Labels: enhancement

#104 [Fix] oauth2 토큰에 idx 추가
  backend/src/main/java/com/hot6/backend/user/UserService.java
  backend/src/main/java/com/hot6/backend/user/model/CustomOAuth2User.java
  backend/src/main/java/com/hot6/backend/user/model/UserDto.java
Labels: Fix

#109 [Feat] 유저 연동 마이페이지 프로필, 펫카드
  backend/src/main/java/com/hot6/backend/pet/PetController.java
  backend/src/main/java/com/hot6/backend/pet/PetService.java
  backend/src/main/java/com/hot6/backend/user/UserController.java
  backend/src/main/java/com/hot6/backend/user/UserService.java
Labels: Fix

#110 [Feat] AWS S3 업로드 기능 추가
  backend/src/main/java/com/hot6/backend/pet/PetController.java
  backend/src/main/java/com/hot6/backend/pet/PetService.java
  backend/src/main/java/com/hot6/backend/pet/S3Service.java
  backend/src/main/java/com/hot6/backend/pet/model/PetDto.java
Labels: Feat

#116 Feature/pet/mypage
  backend/src/main/java/com/hot6/backend/board/post/PostController.java
  backend/src/main/java/com/hot6/backend/board/post/PostRepository.java
  backend/src/main/java/com/hot6/backend/board/post/PostService.java
  backend/src/main/java/com/hot6/backend/board/post/model/PostDto.java
  backend/src/main/java/com/hot6/backend/board/question/QuestionController.java
  backend/src/main/java/com/hot6/backend/board/question/QuestionRepository.java
  backend/src/main/java/com/hot6/backend/board/question/QuestionService.java
  backend/src/main/java/com/hot6/backend/board/question/model/QuestionDto.java
Labels: Fix

#118 [Fix] 답변 조회 기능
  backend/src/main/java/com/hot6/backend/board/answer/AnswerController.java
  backend/src/main/java/com/hot6/backend/board/answer/AnswerRepository.java
  backend/src/main/java/com/hot6/backend/board/answer/AnswerService.java
  backend/src/main/java/com/hot6/backend/board/answer/model/AnswerDto.java
Labels: Fix

#121 [Feat] 일정 생성 기능, 일정 전체 조회 기능 구현 (#22, #26)
  backend/src/main/java/com/hot6/backend/board/answer/AnswerRepository.java
  backend/src/main/java/com/hot6/backend/board/comment/model/CommentDto.java
  backend/src/main/java/com/hot6/backend/board/question/QuestionService.java
  backend/src/main/java/com/hot6/backend/board/question/model/QuestionDto.java
  backend/src/main/java/com/hot6/backend/category/CategoryController.java
  backend/src/main/java/com/hot6/backend/category/model/Category.java
  backend/src/main/java/com/hot6/backend/category/model/CategoryType.java
  backend/src/main/java/com/hot6/backend/chat/repository/ChatRoomRepository.java
  backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java
  backend/src/main/java/com/hot6/backend/config/SecurityConfig.java
  backend/src/main/java/com/hot6/backend/pet/PetController.java
  backend/src/main/java/com/hot6/backend/schedule/ScheduleController.java
  backend/src/main/java/com/hot6/backend/schedule/ScheduleRepository.java
  backend/src/main/java/com/hot6/backend/schedule/ScheduleService.java
  backend/src/main/java/com/hot6/backend/schedule/model/Schedule.java
  backend/src/main/java/com/hot6/backend/schedule/model/ScheduleDto.java
  backend/src/main/java/com/hot6/backend/user/model/User.java
  backend/src/main/resources/application.yml
Labels: Feat

#123 [Feat] provider 추가
  backend/src/main/java/com/hot6/backend/config/filter/JwtFilter.java
  backend/src/main/java/com/hot6/backend/user/CustomOAuth2UserService.java
  backend/src/main/java/com/hot6/backend/user/model/User.java
  backend/src/main/java/com/hot6/backend/user/model/UserDto.java
Labels: Feat

#133 [Feat] 카테고리 기능
  backend/src/main/java/com/hot6/backend/category/CategoryController.java
  backend/src/main/java/com/hot6/backend/category/CategoryService.java
  backend/src/main/java/com/hot6/backend/category/model/Category.java
  backend/src/main/java/com/hot6/backend/category/model/CategoryDto.java
  backend/src/main/java/com/hot6/backend/category/model/CategoryRepository.java
  backend/src/main/java/com/hot6/backend/category/model/CategoryType.java
Labels: Feat

#135 [Fix] 카테고리 기능 강화
  backend/src/main/java/com/hot6/backend/board/post/PostRepository.java
  backend/src/main/java/com/hot6/backend/board/post/PostService.java
  backend/src/main/java/com/hot6/backend/board/post/model/Post.java
  backend/src/main/java/com/hot6/backend/board/post/model/PostDto.java
  backend/src/main/java/com/hot6/backend/board/question/QuestionService.java
  backend/src/main/java/com/hot6/backend/category/model/Category.java
Labels: Fix

#137 Feature/category
  backend/src/main/java/com/hot6/backend/schedule/ScheduleService.java
  backend/src/main/java/com/hot6/backend/schedule/model/Schedule.java
  backend/src/main/java/com/hot6/backend/schedule/model/ScheduleDto.java
  backend/src/main/resources/data.sql
Labels: Fix

#141 [Fix] 반려동물 삭제 오류 해결
  backend/src/main/java/com/hot6/backend/pet/model/Pet.java
  backend/src/main/java/com/hot6/backend/schedule/model/Schedule.java
Labels: Fix

#142 Feature/category
  backend/src/main/java/com/hot6/backend/pet/PetController.java
  backend/src/main/java/com/hot6/backend/pet/PetRepository.java
  backend/src/main/java/com/hot6/backend/pet/PetService.java
  backend/src/main/java/com/hot6/backend/pet/model/Pet.java
  backend/src/main/java/com/hot6/backend/pet/model/PetDto.java
  backend/src/main/java/com/hot6/backend/pet/model/PetStatus.java
  backend/src/main/resources/application.yml
Labels: Fix

#143 [Fix] 펫 카드 수정기능
  backend/src/main/java/com/hot6/backend/pet/PetController.java
  backend/src/main/java/com/hot6/backend/pet/model/PetDto.java
Labels: Fix

#146 [Fix] 최종 펫 카드 수정 오류 해결
  backend/src/main/java/com/hot6/backend/pet/PetService.java
  backend/src/main/java/com/hot6/backend/pet/model/PetDto.java
Labels: Fix

#151 [Feat] 기록 생성 기능, 날짜별 기록 조회 기능 구현 (#29, #24)
  backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java
  backend/src/main/java/com/hot6/backend/daily/model/DailyRecordDto.java
  backend/src/main/java/com/hot6/backend/pet/model/Pet.java
  backend/src/main/java/com/hot6/backend/record/DailyRecordController.java
  backend/src/main/java/com/hot6/backend/record/DailyRecordRepository.java
  backend/src/main/java/com/hot6/backend/record/DailyRecordService.java
  backend/src/main/java/com/hot6/backend/record/model/DailyRecord.java
  backend/src/main/java/com/hot6/backend/record/model/DailyRecordDto.java
  backend/src/main/resources/data.sql
Labels: Feat

#152 [Feat] 알림 기능 미완성
  backend/src/main/java/com/hot6/backend/notification/NotificationController.java
  backend/src/main/java/com/hot6/backend/notification/NotificationRepository.java
  backend/src/main/java/com/hot6/backend/notification/NotificationService.java
  backend/src/main/java/com/hot6/backend/notification/model/Notification.java
  backend/src/main/java/com/hot6/backend/notification/model/NotificationDto.java
  backend/src/main/java/com/hot6/backend/schedule/model/Schedule.java
Labels: Feat

#162 [Feat] 알림 1시간전에 오게 하기
  backend/src/main/java/com/hot6/backend/BackendApplication.java
  backend/src/main/java/com/hot6/backend/notification/NotificationService.java
  backend/src/main/java/com/hot6/backend/notification/ScheduleNotificationScheduler.java
  backend/src/main/java/com/hot6/backend/notification/model/NotificationDto.java
  backend/src/main/java/com/hot6/backend/schedule/ScheduleRepository.java
Labels: Feat

#165 [Feat] 일정/기록 상세 조회 구현, 반려동물별 일정 조회 구현, 날짜별 일정/기록 전체 조회 구현 (#23, #24, #25, #32)
  backend/src/main/java/com/hot6/backend/InitDB.java
  backend/src/main/java/com/hot6/backend/chat/model/ChatDto.java
  backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java
  backend/src/main/java/com/hot6/backend/pet/PetController.java
  backend/src/main/java/com/hot6/backend/record/DailyRecordController.java
  backend/src/main/java/com/hot6/backend/record/DailyRecordRepository.java
  backend/src/main/java/com/hot6/backend/record/DailyRecordService.java
  backend/src/main/java/com/hot6/backend/record/model/DailyRecordDto.java
  backend/src/main/java/com/hot6/backend/schedule/ScheduleController.java
  backend/src/main/java/com/hot6/backend/schedule/ScheduleRepository.java
  backend/src/main/java/com/hot6/backend/schedule/ScheduleService.java
  backend/src/main/java/com/hot6/backend/schedule/model/Schedule.java
  backend/src/main/java/com/hot6/backend/schedule/model/ScheduleDto.java
  backend/src/main/java/com/hot6/backend/user/model/User.java
Labels: Feat

#167 [Feat] 알림 조회 삭제
  backend/src/main/java/com/hot6/backend/notification/NotificationController.java
  backend/src/main/java/com/hot6/backend/notification/NotificationRepository.java
  backend/src/main/java/com/hot6/backend/notification/NotificationService.java
  backend/src/main/java/com/hot6/backend/notification/model/NotificationDto.java
Labels: Feat

#168 [Fix] 오류 수정
  backend/src/main/java/com/hot6/backend/notification/NotificationController.java
  backend/src/main/java/com/hot6/backend/notification/NotificationRepository.java
  backend/src/main/java/com/hot6/backend/notification/NotificationService.java
  backend/src/main/java/com/hot6/backend/notification/ScheduleNotificationScheduler.java
  backend/src/main/java/com/hot6/backend/pet/PetController.java
  backend/src/main/java/com/hot6/backend/schedule/ScheduleRepository.java
Labels: Fix

#171 [Fix] 오류 코드 커스텀
  backend/src/main/java/com/hot6/backend/category/CategoryService.java
  backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java
  backend/src/main/java/com/hot6/backend/common/exception/BaseException.java
  backend/src/main/java/com/hot6/backend/notification/NotificationService.java
  backend/src/main/java/com/hot6/backend/pet/PetService.java
  backend/src/main/java/com/hot6/backend/pet/S3Service.java
Labels: Fix

#173 [Fix] 오류 코드 겹침 해결
  backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java
Labels: Fix

#174 [Fix] 비밀번호 변경 기능
  backend/src/main/java/com/hot6/backend/user/UserController.java
  backend/src/main/java/com/hot6/backend/user/UserService.java
  backend/src/main/java/com/hot6/backend/user/model/UserDto.java
Labels: Fix

#178 [Fix] 알림에 반려동물 이름 추가
  backend/src/main/java/com/hot6/backend/notification/ScheduleNotificationScheduler.java
  backend/src/main/java/com/hot6/backend/notification/model/NotificationDto.java
Labels: Fix

#180 [Fix] 회원가입시 기본 url 적용
  backend/src/main/java/com/hot6/backend/user/UserService.java
  backend/src/main/java/com/hot6/backend/user/model/UserDto.java
Labels: Fix

#181 [Fix] 펫 기본이미지 삽입
  backend/src/main/java/com/hot6/backend/pet/PetService.java
  backend/src/main/java/com/hot6/backend/user/UserService.java
  backend/src/main/resources/application.yml
Labels: Fix

#184 [Chore] 환경변수 설정
  backend/src/main/java/com/hot6/backend/user/OAuth2SuccessHandler.java
  backend/src/main/java/com/hot6/backend/user/UserService.java
  backend/src/main/resources/application.yml
Labels: Chore

#188 [Fix] 닉네임 수정
  backend/src/main/java/com/hot6/backend/user/UserController.java
  backend/src/main/java/com/hot6/backend/user/UserRepository.java
  backend/src/main/java/com/hot6/backend/user/UserService.java
  backend/src/main/java/com/hot6/backend/user/model/UserDto.java
Labels: Fix

#191 [Feat] 회원 탈퇴 & 회원 복구
  backend/src/main/java/com/hot6/backend/admin/AdminController.java
  backend/src/main/java/com/hot6/backend/admin/AdminService.java
  backend/src/main/java/com/hot6/backend/common/BaseResponseStatus.java
  backend/src/main/java/com/hot6/backend/user/UserController.java
  backend/src/main/java/com/hot6/backend/user/UserRepository.java
  backend/src/main/java/com/hot6/backend/user/UserService.java
  backend/src/main/java/com/hot6/backend/user/model/User.java
  backend/src/main/java/com/hot6/backend/user/model/UserDto.java
Labels: Feat

#193 [Fix] 알림 트랙잭션 처리
  backend/src/main/java/com/hot6/backend/notification/NotificationService.java
Labels: Feat

#195 [Fix] 알림 클릭시 이동 처리
  backend/src/main/java/com/hot6/backend/notification/NotificationController.java
  backend/src/main/java/com/hot6/backend/notification/model/NotificationDto.java
Labels: Fix

#196 [Feat] 이메일 중복 확인 기능, 일반/소셜 회원 탈퇴 기능 구현
  backend/src/main/java/com/hot6/backend/config/CustomAuthFailureHandler.java
  backend/src/main/java/com/hot6/backend/config/OAuth2FailureHandler.java
  backend/src/main/java/com/hot6/backend/config/OAuth2SuccessHandler.java
  backend/src/main/java/com/hot6/backend/config/SecurityConfig.java
  backend/src/main/java/com/hot6/backend/config/filter/LoginFilter.java
  backend/src/main/java/com/hot6/backend/user/UserController.java
  backend/src/main/java/com/hot6/backend/user/UserService.java
  backend/src/main/java/com/hot6/backend/user/model/EmailVerify.java
  backend/src/main/java/com/hot6/backend/user/model/User.java
  backend/src/main/java/com/hot6/backend/user/model/UserDto.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
Labels: Feat

#197 [Fix] 로그인 에러 수정
  backend/src/main/java/com/hot6/backend/config/filter/LoginFilter.java
Labels: bug
